### ISSUE TITLE
Not an editor command: Graphviz

### ISSUE THREAD

**Issue by yaohunzhanyue** [liuchengxu/graphviz.vim#5]
Environment: win10, neovim-qt, use plugin default setting

Tried reinstall plugin, won't work.

Any suggestions?

**Comment by liuchengxu** [comment]
Should be an issue of your vimrc/environment, look for help of your plugin manager if you are using that.

**Comment by exapsy** [comment]
I have same issue. Using Vundle, neovim, linux manjaro.

I'm assuming you only tested this with `vim-plug`, since its really the first plugin I ever use that doesn't work with Vundle. Which seems like it's a Plugin's issue, rather than a Plugin Manager issue. So, it doesnt seem wise to keep the issue closed or people won't think of helping to solve it.

(Vundle 22k stars vs vim-plug 21.8k stars - point is they're the same in terms of popularity, it's not weird to assume that someone might be using it instead of vim-plug).

But it would be kind of you if you didn't close issues based on your own assumptions :) You're not only confusing or ignoring users, the way it comes out is as you purposefully choose to reject the fact that its the project's issue at all, which comes out as kinda rude.

The functions though exist (such as `:call graphviz#show()`), the commands are just the only ones that don't work I think.

**Comment by liuchengxu** [comment]
It's not a plugin issue, `ftplugin` only gets loaded when you start to open some buffer, see `:h ftplugin`, I believe you'll have the command with `nvim foo.dot`, for graphviz.vim is intended to be a minimalistic plugin that only loads when you really need it.
